export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    // Solo retorna los children, sin <html> ni <body>
    <>
      {children}
    </>
  );
}
